[SYCL][XPTI] Fix unused function warning with XPTI disabled (#5510)
This function is only used in XPTI instrumentation code which causes a
warning with the latest `gcc`, that trips up the `-Werror` build:

```
/home/nicolas/oneapi/llvm/sycl/source/detail/scheduler/commands.cpp:89:15: error: ‘size_t cl::sycl::detail::deviceToID(const cl::sycl::device&)’ defined but not used [-Werror=unused-function]
   89 | static size_t deviceToID(const device &Device) {
      |               ^~~~~~~~~~
```