Revert "[SYCL][XPTI] Enable PI calls notifications with arguments (#3973)" (#4144)
This reverts commit e239fdf791295e5f57b9bfb949150b67fe6a5412.

The patch introduces build failures like this: 

llvm/sycl/tools/pi-trace/pi_trace.cpp:13:10: fatal error: xpti_trace_framework.h: No such file or directory
   13 | #include "xpti_trace_framework.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.