[SYCL][E2E][NFC] Mark `nthreadsGPU` as `constexpr` (#19964)
`nthreadsGPU` is used to declare an array at 

https://github.com/intel/llvm/blob/sycl/sycl/test-e2e/Regression/commandlist/Inputs/main.cpp#L102
which throws an error:
```
error: variable length arrays in C++ are a Clang extension [-Werror,-Wvla-cxx-extension]
```
This PR marks this variable as constexpr.