Revert "[SYCL][UR] Link UR PI against UR Loader" (#8781)
Reverts intel/llvm#8637

It caused at least 3 known regressions.

1. https://github.com/intel/llvm/pull/8637#issuecomment-1482223287
2.
\sycl\plugins\unified_runtime\ur\adapters\level_zero\ur_level_zero_common.hpp(10):
fatal error C1083: Cannot open include file: 'sycl/detail/pi.h': No such
file or directory
3. ld: error: undefined symbol: pthread_rwlock_wrlock (with GCC 7.5)