[CI][OSSF] Allow package write in sycl-container build (#13245)
After https://github.com/intel/llvm/pull/13173 , we are not able to push
container images.
See
https://github.com/intel/llvm/actions/runs/8485593107/job/23250649681

```
------
 > pushing ghcr.io/intel/llvm/ubuntu2204_base:2f03ef85fee5e867c8250d535f561f2e52e5260c with docker:
------
ERROR: denied: installation not allowed to Write organization package
Error: buildx failed with: ERROR: denied: installation not allowed to Write organization package
```

We need to update the docker images, so need to write packages.

Push permission tested through non PR workflow run here:
https://github.com/intel/llvm/actions/runs/8516878870