Undo a bit of fcf4e360ba6b that confuses MSVC (#7664)
clang\lib\Serialization\GlobalModuleIndex.cpp(818): error C2440:
'initializing': cannot convert from 'const ValueTy' to '_Ty2 &&'
        with
        [
            ValueTy=llvm::SmallVector<unsigned int,2>
        ]
        and
        [
            _Ty2=llvm::SmallVector<unsigned int,2>
        ]

Co-authored-by: Benjamin Kramer <benny.kra@googlemail.com>