[SYCL][NFC] Fix unused StreamName argument (#8607)
Logs:
https://github.com/intel/llvm/actions/runs/4382801939/jobs/7672271805

```
/home/runner/work/llvm/llvm/src/sycl/unittests/xpti_trace/xptitest_subscriber/XPTISubscriber.cpp:47:50: error: unused parameter 'StreamName' [-Werror,-Wunused-parameter]
                                     const char *StreamName) {
                                                 ^
/home/runner/work/llvm/llvm/src/sycl/unittests/xpti_trace/xptitest_subscriber/XPTISubscriber.cpp:52:52: error: unused parameter 'StreamName' [-Werror,-Wunused-parameter]
XPTI_CALLBACK_API void xptiTraceFinish(const char *StreamName) {}
                                                   ^
```