[SYCL] Fix macOS build error (#10776)
Post commit started to failed on
25c3666dffa935c64db513d0db25205e0400c6b7
(https://github.com/intel/llvm/pull/10620) for macOS build because:

```
error: no viable overloaded '='
        ReqdWorkGroupSize = NewReqdWorkGroupSize;

note: candidate function not viable: no known conversion from 'llvm::SmallVector<size_t, 3>' (aka 'SmallVector<unsigned long, 3>') to 'const std::optional<llvm::SmallVector<unsigned long long, 3>>' for 1st argument
    _LIBCPP_INLINE_VISIBILITY optional& operator=(const optional&) = default;