[SYCL][CUDA] fix compilation of CUDA plugin on Windows with MSVC (#10809)
Compilation failed on Windows with Visual Studio 2019/2022 when enabling
the CUDA plugin. This commit fixes compilation by
* adding missing headers
* adding a static_cast of ContextInfoType to fix the following
compilation error:
sycl\plugins\unified_runtime\ur\adapters\cuda\context.cpp(49): error
C2397: conversion from 'ur_context_info_t' to 'uint32_t' requires a
narrowing conversion