[SYCL][Graph] Remove trailing comment whitespace
Fixes post commit CI fail https://github.com/intel/llvm/actions/runs/6470268418/job/17566091513
```
/__w/llvm/llvm/src/sycl/unittests/Extensions/CommandGraph.cpp:1459:12: error: backslash and newline separated by space [-Werror,-Wbackslash-newline-escape]
 1459 |   //     /|\
      |            ^
1 error generated.
```

This was occuring due to a trailing whitespace character in the comment
that was introduced in https://github.com/intel/llvm/pull/11418#discussion_r1352766009