[SYCL] Fix build issues for Debug configuration (#1151)
During the building x64 Debug configuration of Windows using scripts from buildbot folder, there were two issues:
1. OpenCL ICD Loader failed to build because of the missing OpenCL headers
2. Fatal error C1128: clang\lib\Sema\SemaTemplateDeduction.cpp : number of sections exceeded object file format limit: compile with /bigobj

Signed-off-by: Dmitry Vodopyanov <dmitry.vodopyanov@intel.com>