[SYCL] Fix compilation for RHEL 7 with glibc 2.17 and earlier (#4711)
This patch defines macro `__STDC_FORMAT_MACROS` which
was removed from glibc 2.18 to fix the issue 
```
/../dpcpp-compiler/bin/../include/sycl/CL/sycl/queue.hpp:1208:44: error: expected ')'
 "%s:%d: %s: global id: [%" PRIu64 ",%" PRIu64 ",%" PRIu64
```