[SYCL][Graph] Fix Windows build fail
PR https://github.com/intel/llvm/pull/16788 broke the windows
post-commit CI when building with `icx`/`icpx` https://github.com/intel/llvm/actions/runs/13310637099/job/37172065867

```
D:\github\_work\llvm\llvm\build\include\sycl\ext\oneapi\experimental\graph.hpp(577,8): error: 'dllexport' attribute ignored [-Werror,-Wignored-attributes]
  577 | struct __SYCL_EXPORT
      |        ^
D:\github\_work\llvm\llvm\build\include\sycl\detail\export.hpp(23,34): note: expanded from macro '__SYCL_EXPORT'
   23 | #define __SYCL_EXPORT __declspec(dllexport)
      |                                  ^
In file included from D:\github\_work\llvm\llvm\src\sycl\unittests\Extensions\EventMode.cpp:9:
In file included from D:\github\_work\llvm\llvm\build\include\sycl\sycl.hpp:11:
In file included from D:\github\_work\llvm\llvm\build\include\sycl\detail\core.hpp:23:
In file included from D:\github\_work\llvm\llvm\build\include\sycl\queue.hpp:34:
D:\github\_work\llvm\llvm\build\include\sycl\ext\oneapi\experimental\graph.hpp(587,8): error: 'dllexport' attribute ignored [-Werror,-Wignored-attributes]
  587 | struct __SYCL_EXPORT
      |        ^
D:\github\_work\llvm\llvm\build\include\sycl\detail\export.hpp(23,34): note: expanded from macro '__SYCL_EXPORT'
   23 | #define __SYCL_EXPORT __declspec(dllexport)
      |                                  ^
2 errors generated.
```

Fix by not exporting these symbols