Fix errorTo function signature with unused attribute
ErrorHelper.h:19:19: error: unused function template 'errorTo' [-Werror,-Wunused-template]

this fixes error