[SYCL] Disambiguate atomic_ref references (intel/llvm-test-suite#545)
According to SYCL 2020, the atomic_ref type must become standard and be
placed into the sycl:: namespace. So, when two atomic_ref types are there,
the sycl::atomic_ref and sycl::ext::oneapi::atomic_ref ones, the reference
to atomic_ref will become ambiguous:

  SYCL/AtomicRef/sub.h(132,20): error: reference to 'atomic_ref' is ambiguous

To disambiguate the atomic_ref reference, the fully qualified name is used
in the tests.

Signed-off-by: Pavel Samolysov <pavel.samolysov@intel.com>