[SYCL][Graph] Correct assert usage (#10969)
Fix [macOS CI fail in post-commit
CI](https://github.com/intel/llvm/actions/runs/5975037762/job/16210261083)
by asserting on `false`, then providing the error string.

Error 
```
/Users/runner/work/llvm/llvm/src/sycl/source/detail/graph_impl.cpp:140:16: error: implicit conversion turns string literal into bool: 'const char[55]' to 'bool' [-Werror,-Wstring-conversion]
        assert("Node duplication failed. A duplicated node is missing.");
        ~~~~~~~^~~~~~~~~~~~~~~~~~~
```

---------

Co-authored-by: Pablo Reble <pablo.reble@intel.com>