Add cstdlib include to backtrace_lin.cpp
llvm 24 removes transitive includes for libc++ so cstdlib needs to be included, the error was this

backtrace_lin.cpp:30:5: error: use of undeclared identifier 'free'