[SYCL] Fix post commit after PR 2292
This patch fixes post commit caused by incorrect declaration
of `cl` namespace:

https://github.com/intel/llvm/runs/2838178517:

```
In file included from /home/runner/work/llvm/llvm/src/sycl/unittests/scheduler/FailedCommands.cpp:10:
/home/runner/work/llvm/llvm/src/sycl/unittests/scheduler/SchedulerTestUtils.hpp:25:11: error: inline namespace reopened as a non-inline namespace [-Werror,-Winline-namespace-reopened-noninline]
namespace cl {
          ^
inline 
/home/runner/work/llvm/llvm/src/sycl/source/detail/stream_impl.hpp:20:25: note: previous definition is here
__SYCL_INLINE_NAMESPACE(cl) {
                        ^
1 error generated.
```