[SYCL] Rename `detail::memcpy` to `detail::memcpy_no_adl` (#14836)
`detail::memcpy`, even though in a different namespace, can cause
ambiguity with libc's `memcpy`, due to argument dependent lookup (ADL).
For example, the compiler throws a compilation error due to `memcpy`
ambiguity in the following code:
```
#include <sycl/vector.hpp>

template <typename T>
void foo(T *dst, T *src, size_t count) {
          memcpy(dst, src, count * sizeof(T));
}

using T = sycl::vec<int, 1>;

SYCL_EXTERNAL void bar(T *dst, T *src, size_t count) {
          foo(dst, src, count * sizeof(T));
}
```

Compilation error:
```
memcpy_test.cpp:5:4: error: call to 'memcpy' is ambiguous
    5 |           memcpy(dst, src, count * sizeof(T));
      |           ^~~~~~
memcpy_test.cpp:11:4: note: in instantiation of function template specialization 'foo<sycl::vec<int, 1>>' requested here
   11 |           foo(dst, src, count * sizeof(T));
      |           ^
/usr/include/string.h:43:14: note: candidate function
   43 | extern void *memcpy (void *__restrict __dest, const void *__restrict __src,
      |              ^
llvm/build/bin/../include/sycl/detail/memcpy.hpp:16:13: note: candidate function
   16 | inline void memcpy(void *Dst, const void *Src, size_t Size) {
      |             ^
1 error generated.
```

To fix this error, this PR renames `detail::memcpy` to
`detail::memcpy_no_adl`