[L0] fix linkage for urPhysicalMemGetInfo on Windows
Including ur_interface_loader.hpp in v2 adapter causes error C2375
as urPhysicalMemGetInfo is declared without UR_APIEXPORT UR_APICALL