[SYCL] Shortening error messages in annotated_arg/ptr assertion failures (#11730)
This change shortens the error messages for the static assertion
failures for annotated_arg/ptr. The check is first assigned to a boolean
variable that is named to represent the check and this variable is used
in the static assertion. This prevents the props for annotated_arg/ptr
to printed in the error message.

For example, the following static assertion: 

```
error: static assertion failed due to requirement 'is_valid_property<ac_int<17, true>, sycl::ext::oneapi::experimental::property_value<sycl::ext::intel::experimental::buffer_location_key, std::integral_constant<int, 0>>>::value': Property is invalid for the given type.
   57 |   static_assert(is_valid_property<T, Prop>::value,
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

will look like this: 

```
error: static assertion failed due to requirement 'is_valid_property_for_given_type': Property is invalid for the given type.
   59 |   static_assert(is_valid_property_for_given_type,
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```