[SYCL] Fix CTAD-related issue with std::lock_guard (#8883)
This patch fixes post-commit failure introduced in
https://github.com/intel/llvm/pull/7468:

```
/Users/runner/work/llvm/llvm/src/sycl/source/detail/program_manager/program_manager.cpp:1324:9: error: 'lock_guard' may not intend to support class template argument deduction [-Werror,-Wctad-maybe-unsupported]
        std::lock_guard HostPipesGuard(m_HostPipesMutex);
        ^
```