Make pragma region names joined by _
On Windows the region name `usm import release (experimental)` cause
compile errors in certain situations which look like this:

```
error C7586: a 'import' directive must end with a ';' on the same line
```

This patch replaces spaces with `_` in the region names to avoid this
compile error.