[SYCL] Improve error diagnostic for invalid SYCL kernel name (#4867)
According to SYCL 2020 spec:
The kernel name must be forward declarable at namespace scope (including global namespace scope) and may not be forward declared other than at namespace scope.

The use of nested struct-case (where the name IS globally visible but just not forward-declarable) in a SYCL kernel name currently generates invalid error message:

error: '{{.*}}' should be globally visible

This patch modifies the error diagnostic message when the kernel name is declared at non-namespace scope (i.e. Inside a function or class/struct).

Signed-off-by: Soumi Manna soumi.manna@intel.com