[SYCL] Use explicit return type in `get_vec_idx` helper (#16464)
Apparently, some versions of MSVC (e.g. 14.29.30133) fail to compile it

```
error C3779: 'sycl::_V1::detail::SwizzleOp<VecT,OperationLeftT,OperationRightT,OperationCurrentT,Indexes...>::get_vec_idx': a function that returns 'auto' cannot be used before it is defined
```

when used with `-fsycl-host-compiler`. This has been caught by the
existing `bit_cast_win.cpp` test in a downstream environment.