Fix MergeBlock error: a merge block for another header (#3280)
Code was assigning the same merge block to multiple headers. Added a
fails as follows before the fix:

```
[3/4] Running the LLVM-SPIRV regression tests
llvm-lit: /space/pvelesko/.local/lib/python3.10/site-packages/lit/llvm/config.py:502: note: using clang: /space/pvelesko/install/llvm/21.0-upstream/bin/clang
FAIL: LLVM_SPIRV :: OpLoopMerge_mergeBlock.ll (1 of 918)
******************** TEST 'LLVM_SPIRV :: OpLoopMerge_mergeBlock.ll' FAILED ********************
Exit Code: 1

Command Output (stderr):
--
RUN: at line 5: /space/pvelesko/SPIRV-LLVM-Translator/build/tools/llvm-spirv/llvm-spirv /space/pvelesko/SPIRV-LLVM-Translator/test/../mergeBlock.bc -o /space/pvelesko/SPIRV-LLVM-Translator/build/test/test_output/Output/OpLoopMerge_mergeBlock.ll.tmp.spv
+ /space/pvelesko/SPIRV-LLVM-Translator/build/tools/llvm-spirv/llvm-spirv /space/pvelesko/SPIRV-LLVM-Translator/test/../mergeBlock.bc -o /space/pvelesko/SPIRV-LLVM-Translator/build/test/test_output/Output/OpLoopMerge_mergeBlock.ll.tmp.spv
RUN: at line 6: /usr/local/bin/spirv-val /space/pvelesko/SPIRV-LLVM-Translator/build/test/test_output/Output/OpLoopMerge_mergeBlock.ll.tmp.spv
+ /usr/local/bin/spirv-val /space/pvelesko/SPIRV-LLVM-Translator/build/test/test_output/Output/OpLoopMerge_mergeBlock.ll.tmp.spv
error: line 111: Block '46[%_Z11round_robiniiiPViS0__exit_loopexit]' is already a merge block for another header
  %_Z15gpu_round_robiniiiPViS0_ = OpFunction %void None %32
```

Original commit:
https://github.com/KhronosGroup/SPIRV-LLVM-Translator/commit/9e823ad46a81502