[SYCL] Fix Windows build configure issue (#6060)
Error: "Threads::Threads" but the target was not found.  Perhaps a
find_package() call is missing for an IMPORTED target, or an ALIAS
target is missing?