[Clang] Fix conflict resolution use return instead of break
To avoid causing unexpected failures
clang/test/CodeGenSYCL/native_cpu_mangling.cpp:15:73:
error: cannot mangle this calling convention yet