[SYCL] Fix the unused parameter warnings in the level_zero backend
When the compiler is built with -Werror argument, the following errors
occur:

include/sycl/ext/oneapi/backend/level_zero.hpp:125:26: error: unused parameter 'Handler' [-Werror,-Wunused-parameter]
    const async_handler &Handler) {
                         ^
include/sycl/ext/oneapi/backend/level_zero.hpp:136:55: error: unused parameter 'Handler' [-Werror,-Wunused-parameter]
    const context &TargetContext, const async_handler Handler) {
                                                      ^
2 errors generated.

In order to not break the API, the parameters is still declared in the
function's signatures but marked as unused via the (void)Handler
expressions.