[DeviceSanitizer] Ensure __USE_SPIR_BUILTIN__ has a value (#16570)
Ensure that `__USE_SPIR_BUILTIN__` is defined to the value `0` when
`defined(__SPIR__) || defined(__SPIRV__)` is false to fix build errors
like this:

libdevice/include/sanitizer_defs.hpp:51:25: error: expected value in
expression
       51 | #if __USE_SPIR_BUILTIN__
          |                         ^