[SYCL][Driver][NFC] Fix unused variable warning (#5792)
llvm/clang/lib/Driver/Driver.cpp:9141:13:
   error: unused variable 'Ext' [-Werror,-Wunused-variable]
      StringRef Ext(llvm::sys::path::extension(FileName).drop_front());