[SYCL] Suppress warning for use of dllimport/dllexport attribute when compile with -fsycl.
The change do following:
1>	Suppress warning for "_declspec attribute 'dllexport' is not
supported" when run with -fsycl
2>	Emit error when import function is called in the sycl kernel.

For example: for the test following:

bash-4.2$ clang -cc1 -triple spir64-unknown-windows-sycldevice
-fsycl-is-device -fms-extensions sycl-dllimport-dllexport.cpp

sycl-dllimport-dllexport.cpp:10:48: error: SYCL kernel cannot call a
dllimport function
  kernel_single_task<class fake_kernel>([]() { bar(); });
                                               ^
sycl-dllimport-dllexport.cpp:1:28: note: 'bar' declared here
int __declspec(dllimport) bar();
		          ^
1 error generated.
=== test ==
int __declspec(dllimport) bar();

template <typename name, typename Func> __attribute__((sycl_kernel))
void kernel_single_task(Func kernelFunc) {
    kernelFunc();
}
int main() {
 t status
 kernel_single_task<class fake_kernel>([]() { bar(); });
  return 0;
}

Signed-off-by: Yu <jennifer.yu@intel.com>