[SYCL] remove unused class field (#17970)
This PR is quick fix to avoid error 
clang/lib/Sema/SemaSYCL.cpp:6584:25: error: private field 'Policy' is
not used [-Werror,-Wunused-private-field]