Fix CI warning in reduction.hpp
Using a sycl::reduction in a graphs unittests
caused the build to fail with a sign compare
warning
```
/__w/llvm/llvm/build/include/sycl/reduction.hpp:1358:56: error: comparison of integer expressions of different signedness: 'int' and 'const size_t' {aka 'const long unsigned int'} [-Werror=sign-compare]
```