[SYCL] Move SYCL headers from standard clang location (#1308)
SYCL headers were moved from default clang include directory
(lib/clang/11.0.0/include) to (include/sycl) to support mixed
compilers (e.g. gcc for host code and clang for device code)
during build of SYCL application.

Clang driver adds new directory to system include search path.

For non-clang compilers the user should add option below to
compiler command line to let it find SYCL headers:
-I <path_to_sycl_compiler>/include/sycl

Additional diagnostic can be raised depending on compiler
which is used (see examples for clang below). It can be ignored.

/localdisk2/bbsycl/res/include/sycl/CL/__spirv/spirv_ops.hpp:74:8: error: SYCL 1.2.1 specification does not allow 'sycl_device' attribute applied to a function with a raw pointer parameter type [-Wsycl-strict]
  extern SYCL_EXTERNAL __ocl_event_t __spirv_GroupAsyncCopy(

/localdisk2/bbsycl/res/include/sycl/CL/sycl/ordered_queue.hpp:267:37: warning: 'ordered_queue' is deprecated: Replaced by in_order queue property [-Wdeprecated-declarations]
  size_t operator()(const cl::sycl::ordered_queue &q) const {

Signed-off-by: Vladimir Lazarev vladimir.lazarev@intel.com