Merge InlineAsm test changes
commit 7dec03995872a7b9c81b71777d1214b84b73843b
Author: Garcia Orozco, David <david.garcia.orozco@intel.com>
Date:   Mon Jan 27 10:21:05 2025 -0800

    remove IntelGPU folder, and add target-spir to lit.local.cfg

commit dccac19b948a18593093fea0a2a03d4fda795c31
Author: Garcia Orozco, David <david.garcia.orozco@intel.com>
Date:   Mon Jan 27 10:09:58 2025 -0800

    Use target features instead of backend features

commit be87b968c68baeb89d09b811bc05e1cf21a0e493
Merge: d83a37d5b8c0 e923fbbb2d53
Author: Garcia Orozco, David <david.garcia.orozco@intel.com>
Date:   Mon Jan 27 10:06:53 2025 -0800

    Merge branch 'sycl' into inlineasm-litlocal

commit e923fbbb2d5307e4d72d3c1dbd699cf9edbafb81
Author: Nick Sarnie <nick.sarnie@intel.com>
Date:   Tue Jan 28 03:01:42 2025 +0900

    [CI] Update dev-igc even if IGC CI failed (#16790)

    IGC public CI has been failing for months and we got confirmation even
    if the public CI fails the change has already been internally validated.
    We can confirm this change works as below:
    [Old
    link](https://api.github.com/repos/intel/intel-graphics-compiler/actions/workflows/build-IGC.yml/runs?status=success)
    [New
    link](https://api.github.com/repos/intel/intel-graphics-compiler/actions/workflows/build-IGC.yml/runs)

    Signed-off-by: Sarnie, Nick <nick.sarnie@intel.com>

commit 4eb095e92984358ed4e52639ae15d83f549aebde
Author: Chris Perkins <chris.perkins@intel.com>
Date:   Mon Jan 27 09:34:35 2025 -0800

    [SYCL] remove experimental online_compiler extension (#16776)

    Minus support for "CM", all the functionality of the old experimental
    online_compiler extension is being provided by the new (also
    experimental) kernel_compiler. Only better.

    Besides always being merely experimental, the online_compiler has been
    marked as deprecated for over a year, it has become burdensome to
    continue to support, and it sometimes confuses users. The decision has
    been made to remove it, without waiting for an ABI breaking window.

commit 566f5149ade9575c3ba8b8f634173972ffb04b13
Author: Udit Kumar Agarwal <udit.agarwal@intel.com>
Date:   Mon Jan 27 09:27:27 2025 -0800

    [CI] Install `pkg-config` in docker container (#16797)

    `pkg-config` is required for `llvm-spirv` to detect `spirv-tools`
    installation.
    See https://github.com/intel/llvm/pull/16743#issuecomment-2614079031 for
    more info.

commit 367f35573e2d93651256486783b8f2c8c547cd8e
Author: Mészáros Gergely <gergely.meszaros@intel.com>
Date:   Mon Jan 27 17:28:39 2025 +0100

    [SYCL][E2E][NFC] Fix NameError if directive fails to parse (#16767)

    Currently if a test contains a malformed directive, the following
    exception is raised along with the original parsing error:
    ```plaintext
    Exception during script execution:
    (original error)

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "llvm/llvm/utils/lit/lit/worker.py", line 76, in _execute_test_handle_errors
        result = test.config.test_format.execute(test, lit_config)
      File "llvm/sycl/test-e2e/format.py", line 232, in execute
        script = self.parseTestScript(test)
      File "llvm/sycl/test-e2e/format.py", line 105, in parseTestScript
        return lit.Test.Result(Test.UNRESOLVED, str(e))
    NameError: name 'Test' is not defined
    ```
    The test ends up as UNRESOLVED either way, but fixing it is easy and
    improves the error message greatly.

commit d83a37d5b8c0d0d5ec9ba280ab5d4654048955f9
Author: Garcia Orozco, David <david.garcia.orozco@intel.com>
Date:   Wed Jan 22 13:47:59 2025 -0800

    Add `InlineAsm/IntelGPU` test directory

commit 745d9b5e7f4dc8c2faf26e3b50309d79394dcd90
Merge: e91210ef1e3d 34ef8668fcdc
Author: Garcia Orozco, David <david.garcia.orozco@intel.com>
Date:   Wed Jan 22 13:33:25 2025 -0800

    Merge branch 'sycl' into inlineasm-litlocal

commit e91210ef1e3d61f1738d2b977716ba8244bf3fca
Merge: 8d5f5170407d 38e6e1bf599c
Author: Garcia Orozco, David <david.garcia.orozco@intel.com>
Date:   Mon Jan 20 11:59:42 2025 -0800

    Merge branch 'sycl' into inlineasm-litlocal

commit 8d5f5170407db91ff9b090d81a1f27710e809c8e
Author: Garcia Orozco, David <david.garcia.orozco@intel.com>
Date:   Mon Dec 9 11:51:56 2024 -0800

    Add REQUIRES: gpu,linux to lit.local.cfg

commit a518866fc4db6d12aa4960755aad45285d2ad2ea
Author: Garcia Orozco, David <david.garcia.orozco@intel.com>
Date:   Mon Dec 9 11:44:21 2024 -0800

    Use lit.local.cfg to mark cuda and hip as unsupported