[SYCL] Improve diagnostics for invalid kernel names (#4769)
The use of lambda (which is not forward-declarable) in a SYCL kernel name currently generates the error message: 
error: unnamed lambda ‘(lambda at {{.*}}filename.cpp{{.}’ used

The diagnostic message is very confusing and doesn't help to understand what exactly is wrong. 

To update the message to make it better and more helpful, this patch modifies the error diagnostic when the lambdas (anonymous function object types) are used in SYCL kernel names.

Signed-off-by: Soumi Manna <soumi.manna@intel.com>